create database customer_behavior;
use customer_behavior;

select * from customer
limit 20;

-- 1  whatis the total revenue generated by male vs femanle customers?

select gender,sum(purchase_amount) as total_revenue from customer
group by gender;

-- 2 which customer used a discount but still spent more then the average purchase amount?

select customer_id, purchase_amount from customer
where discount_applied = "Yes" and purchase_amount > (select avg(purchase_amount) from customer);

-- 3 which are the top 5 products with the highest average review rating

select item_purchased, round(avg(review_rating),2) as "Average Product Rating"from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;


-- 4 compare the average Purchase Amounts between Standard and Express Shipping?

select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount from customer
where shipping_type in ("Standard" ,"Express")
group by shipping_type;

-- 5 do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subcribers?

select subscription_status,
count(customer_id) as total_customer,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

-- 6 which 5 products have the highest percentage of purchases with discount applied?

select item_purchased,
round(
		sum(case when discount_applied = 'Yes' then 1
				else 0 end) / count(*) * 100,2) as discount_rate
			from customer
			group by item_purchased
			order by discount_rate desc
			limit 5;
            
-- 7 segment customer into new returning and loyal based on their total number of previous purchases, and show the count of each segment?

with customer_type as (
select customer_id, previous_purchases,
case when previous_purchases = 1 then "New"
when previous_purchases between 2 and 10 then "Returning"
else "Loyal"
end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customer"
from customer_type
group by customer_segment;

-- 8 what are top 3 most purchased product with in each category?

with item_count as(
select category,
item_purchased,
count(customer_id) as total_order ,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer 
group by category, item_purchased
)

select item_rank, category, item_purchased, total_order
from item_count
where item_rank <= 3;


-- 9 Are customer who repeat buyers (more than 5 previour purchases) also likely to subscribe?

select subscription_status, 
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;


-- 10 what is the revenue contribution of each age group ?


select age_group,
sum(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc;


